### PR TITLE
Fix survey page for arrival via reservation checkout page

### LINKED ISSUE #681: 500 in `submit_survey` view when attempting to cast a value to an integer
```
Internal Server Error: /survey/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/app/apps/core/decorators.py", line 91, in wrapper
    return view_fn(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 33, in routed
    return req_method(request, *args2, **kwargs2)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 125, in newreq
    outp = req_function(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 106, in newreq
    outp = req_function(request, *args, **kwargs)
  File "/opt/app/apps/survey/views.py", line 199, in submit_survey
    return _create_survey_and_trees(request)
  File "/usr/local/lib/python2.7/dist-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/opt/app/apps/survey/views.py", line 233, in _create_survey_and_trees
    blockface = survey.blockface
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 568, in __get__
    qs = qs.filter(**params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 691, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 709, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1331, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1358, in _add_q
    current_negated=current_negated, connector=connector)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1230, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1138, in build_lookup
    return final_lookup(lhs, rhs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/lookups.py", line 82, in __init__
    self.rhs = self.get_prep_lookup()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_lookup(self.lookup_name, self.rhs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 646, in get_prep_lookup
    return self.get_prep_value(value)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 915, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

### PR DESCRIPTION
**Pull request by RickMohr**
Update `blockfaceId` when user clicks a blockface. Fixes #681.

### CODE REVIEW

File: src/nyc_trees/js/src/surveyPage.js [hunk 1]
```diff
@@ -58,12 +61,11 @@ var tileLayer = mapModule.addTileLayer(blockfaceMap),
             $(dom.selectSide).addClass('hidden');
             $(dom.btnNextGroup).addClass('hidden');
 
-            mapUtil.zoomToBlockface(blockfaceMap, gridData.id);
+            mapUtil.zoomToBlockface(blockfaceMap, blockfaceId);
             return true;
         }
     });
 
-blockfaceMap.addLayer(grid);
```
Comment (maurizi) [inline src/nyc_trees/js/src/surveyPage.js]: Uh... don't we need the grid layer?

Comment (RickMohr) [inline src/nyc_trees/js/src/surveyPage.js]: Yes but we don't need to add it twice. It's added when created:
```
    grid = mapModule.addGridLayer(blockfaceMap)
```

Comment (kdeloach) [inline src/nyc_trees/js/src/surveyPage.js]: Looks like there is now a `addGridLayer` method on the map module that is called earlier on.

**Comment by kdeloach** [comment]
+1 Tested and it working.
